cart/urls.py
from django.urls import path

from cart.views import CartAdd, CartUpdate, CartRemove, CartView

app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart_detail'),
    path('add/', CartAdd.as_view(), name='cart_add'),
    path('update/<str:sku>', CartUpdate.as_view(), name='cart_update'),
    path('remove/<str:sku>', CartRemove.as_view(), name='cart_remove'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from config import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('cooperation/', include('cooperation.urls', namespace='cooperation')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('core.urls', namespace='core')),
]

if settings.DEBUG:

    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls'))
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from core.views import HomePageView, ProductsListView, ProductView, ProfileView

app_name = 'core'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('category/<slug:slug>/', ProductsListView.as_view(), name='category'),
    path('product/<slug:slug>/', ProductView.as_view(), name='product'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

orders/urls.py
from django.urls import path

from orders.views import OrderCreateView, CreatedOrderView, OrderListView

app_name = 'orders'

urlpatterns = [
    path('list', OrderListView.as_view(), name='orders_list'),
    path('create', OrderCreateView.as_view(), name='create'),
    path('created/<int:pk>', CreatedOrderView.as_view(), name='created'),
]

cart/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import ProductPack
from cart.forms import CartUpdateProductForm

User = get_user_model()


class Cart(models.Model):
    user = models.ForeignKey(User,
                             verbose_name='Клиент',
                             related_name='cart',
                             on_delete=models.CASCADE)
    pack = models.ForeignKey(ProductPack,
                             verbose_name='Фасовка',
                             related_name='cart',
                             on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField('Количество')

    class Meta:
        ordering = ['pack__product__name']

    def get_total_weight(self) -> int:
        return self.pack.get_package_weight() * self.quantity

    def get_total_price(self) -> float:
        return self.pack.get_package_price() * self.quantity

    def get_update_form(self) -> CartUpdateProductForm:
        form = CartUpdateProductForm({'quantity': self.quantity})
        return form

cart/forms.py
from django.core.exceptions import ValidationError
from django import forms
from django.forms import BaseFormSet


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(label='', min_value=0,
                                  max_value=999, required=False)
    sku = forms.CharField(widget=forms.HiddenInput)


class CartUpdateProductForm(forms.Form):
    quantity = forms.IntegerField(label='', min_value=1, max_value=999)


class BaseAddProductFormSet(BaseFormSet):
    def clean(self):
        if any(self.errors):
            return
        if not any(map(lambda x: x.cleaned_data.get('quantity'), self.forms)):
            raise ValidationError('Не заполнена ни одна форма.')

cart/views.py
from decimal import Decimal

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, F
from django.forms import formset_factory
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, View, DeleteView, UpdateView

from cart.models import Cart
from cart.forms import CartAddProductForm, BaseAddProductFormSet
from core.models import ProductPack


class CartView(LoginRequiredMixin, ListView):

    template_name = 'cart/cart.html'
    context_object_name = 'cart'

    def get_queryset(self):
        user_cart = Cart.objects.filter(user=self.request.user).\
            select_related('pack__product')
        return user_cart

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.object_list:
            # total_price = sum([item.get_total_price() for item in self.object_list])
            total_price = self.object_list.aggregate(tp=Sum(F('quantity') *
                                                            F('pack__price') *
                                                            F('pack__items_in_box'))).\
                get('tp').quantize(Decimal('1.00'))
            context['total_price'] = total_price

        context['title'] = 'Корзина'
        return context


class CartAdd(LoginRequiredMixin, View):

    def post(self, request):

        FormSet = formset_factory(CartAddProductForm, formset=BaseAddProductFormSet)
        formset = FormSet(request.POST)

        if formset.is_valid():
            cd = formset.cleaned_data
            for item in cd:
                if item.get('quantity'):
                    pack = ProductPack.objects.get(sku=item.get('sku'))
                    cart, _ = Cart.objects.get_or_create(user=request.user,
                                                         pack=pack,
                                                         defaults={'quantity': 0})
                    cart.quantity += item.get('quantity')
                    cart.save()
        return redirect('cart:cart_detail')


class CartUpdate(LoginRequiredMixin, UpdateView):

    fields = ('quantity',)
    slug_url_kwarg = 'sku'
    slug_field = 'pack__sku'

    success_url = reverse_lazy('cart:cart_detail')

    def get_queryset(self):
        return Cart.objects.filter(user=self.request.user)


class CartRemove(LoginRequiredMixin, DeleteView):

    def get_queryset(self):
        return Cart.objects.filter(user=self.request.user)

    slug_field = 'pack__sku'

    slug_url_kwarg = 'sku'
    success_url = reverse_lazy('cart:cart_detail')


# @login_required
# @require_POST
# def cart_update(request, sku):
#     form = CartUpdateProductForm(request.POST)
#     if form.is_valid():
#         cd = form.cleaned_data
#         pack = ProductPack.objects.get(sku=sku)
#         Cart.objects.filter(user=request.user, pack=pack).\
#             update(quantity=cd.get('quantity'))

#     return redirect('cart:cart_detail')


# @login_required
# @require_POST
# def cart_remove(request, sku):
#     pack = ProductPack.objects.get(sku=sku)
#     cart = Cart.objects.filter(user=request.user, pack=pack)
#     cart.delete()

#     return redirect('cart:cart_detail')

cart/templates/cart/cart.html
{% extends 'core/base.html' %}
{% load static %}
{% load weight_converter %}

{% block content %}
  <h1>Ваша корзина</h1>
  <table class="table table-secondary">
    <thead>
      <tr>
      <th>Фото</th>
      <th>Товар</th>
      <th>Вес</th>
      <th>Цена</th>
      <th>Вложений в упаковке</th>
      <th>Вес упаковки</th>
      <th>Кол-во упаковок</th>
      <th>Общий вес</th>
      <th>Стоимость</th>
      <th>Удалить</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        <tr>
          <td>
            <a href="{% url "core:product" item.pack.product.slug %}">
              <img src="{{ item.pack.product.image.url }}" height="80px">
            </a>
          </td>
          <td>{{ item.pack.product.name }}</td>
          <td>{{ item.pack.weight | convert_weight }}</td>
          <td>{{ item.pack.price }}</td>
          <td>{{ item.pack.items_in_box }} шт</td>
          <td>{{ item.pack.get_package_weight | convert_weight }}</td>
          <td>
            <form action="{% url "cart:cart_update" item.pack.sku %}" method="post">
              {{ item.get_update_form.as_p }}
              <input type="submit" value="Изменить">
              {% csrf_token %}
            </form>
          </td>
          <td>{{ item.get_total_weight | convert_weight }}</td>
          <td>{{ item.get_total_price }}</td>
          <td>
            <form action="{% url "cart:cart_remove" item.pack.sku %}" method="post">
              <input type="submit" value="Удалить">
              {% csrf_token %}
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% if cart %}
  <p>Итоговая стоимость: {{ total_price }}</p>
  {% endif %}
  <p class="text-right">
    <a href="{% url "core:category" "waffles" %}" class="button light">В каталог</a>
    {% if cart.count %}
    <a href="{% url "orders:create" %}" class="button">Оформить</a>
    {% endif %}
  </p>
{% endblock %}