cart/urls.py
from django.urls import path

from cart.views import CartAdd, CartUpdate, CartRemove, CartView

app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart_detail'),
    path('add/', CartAdd.as_view(), name='cart_add'),
    path('update/<str:sku>', CartUpdate.as_view(), name='cart_update'),
    path('remove/<str:sku>', CartRemove.as_view(), name='cart_remove'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from config import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('cooperation/', include('cooperation.urls', namespace='cooperation')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('core.urls', namespace='core')),
]

if settings.DEBUG:

    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls'))
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cooperation/urls.py
from django.urls import path

from cooperation.views import CooperationCreateView

app_name = 'cooperation'

urlpatterns = [
    path('distribution', CooperationCreateView.as_view(),
         {'type': 'distribution'}, name='distribution'),
    path('private_label', CooperationCreateView.as_view(),
         {'type': 'private_label'}, name='private_label'),
    path('suppliers', CooperationCreateView.as_view(),
         {'type': 'suppliers'}, name='suppliers'),
]

core/urls.py
from django.urls import path

from core.views import HomePageView, ProductsListView, ProductView, ProfileView

app_name = 'core'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('category/<slug:slug>/', ProductsListView.as_view(), name='category'),
    path('product/<slug:slug>/', ProductView.as_view(), name='product'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

orders/urls.py
from django.urls import path

from orders.views import OrderCreateView, CreatedOrderView, OrderListView

app_name = 'orders'

urlpatterns = [
    path('list', OrderListView.as_view(), name='orders_list'),
    path('create', OrderCreateView.as_view(), name='create'),
    path('created/<int:pk>', CreatedOrderView.as_view(), name='created'),
]

core/models.py
from decimal import Decimal

from django.db import models
from django.urls import reverse

from core.utils import path_category_image, path_product_image


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_published=True)


class Product(models.Model):
    name = models.CharField('Наименование', max_length=255)
    slug = models.SlugField('URL', max_length=255, unique=True)
    type = models.ForeignKey('ProductType', verbose_name='Тип',
                             on_delete=models.PROTECT)
    image = models.ImageField('Фото', upload_to=path_product_image,
                              default='images/default.jpg')
    is_gost = models.BooleanField('Соответствует ГОСТ')
    is_published = models.BooleanField('Доступен', default=True)

    objects = models.Manager()
    published = PublishedManager()

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self) -> str:
        return reverse('core:product', kwargs={'slug': self.slug})

    def display_category(self) -> str:
        return self.type.category

    display_category.short_description = 'Категория'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ('name',)


class ProductDetail(models.Model):

    CHOICES = (
        ('DAYS', 'дней'),
        ('MOUNTHS', 'мес')
    )

    product = models.OneToOneField('Product', verbose_name='Товар',
                                   null=True, on_delete=models.SET_NULL)
    description = models.TextField('Описание', blank=True)
    conditions = models.TextField('Условия хранения', blank=True)
    storage_time = models.PositiveIntegerField('Срок хранения')
    storage_time_units = models.CharField('Единицы измерения', max_length=7,
                                          choices=CHOICES, default='MOUNTHS')
    calories = models.FloatField('Калорийность')
    proteins = models.FloatField('Белки')
    fats = models.FloatField('Жиры')
    carbohydrates = models.FloatField('Углеводы')

    class Meta:
        verbose_name = 'Характеристики товара'
        verbose_name_plural = 'Характеристики товара'


class ProductPack(models.Model):
    product = models.ForeignKey('Product', verbose_name='Товар',
                                null=True,
                                on_delete=models.CASCADE,
                                related_name='pack')
    sku = models.CharField('Артикул', max_length=50, unique=True)
    weight = models.PositiveIntegerField('Вес, грамм')
    items_in_box = models.PositiveIntegerField('Вложение, шт')
    price = models.DecimalField('Цена', max_digits=8, decimal_places=2)

    is_published = models.BooleanField('Доступен', default=True)

    objects = models.Manager()
    published = PublishedManager()

    def __str__(self) -> str:
        return self.sku

    def get_package_weight(self) -> int:
        return self.weight * self.items_in_box

    def get_package_price(self) -> Decimal:
        pp = self.price * self.items_in_box
        return pp.quantize(Decimal('1.00'))

    class Meta:
        verbose_name = 'Фасовка'
        verbose_name_plural = 'Фасовка'


class ProductType(models.Model):
    name = models.CharField('Тип', max_length=100, db_index=True)
    slug = models.SlugField('URL', max_length=255, unique=True)
    category = models.ForeignKey('Category', verbose_name='Категория',
                                 on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = 'Тип товара'
        verbose_name_plural = 'Типы товаров'
        ordering = ('name',)


class Category(models.Model):
    name = models.CharField('Категория', max_length=100)
    slug = models.SlugField('URL', max_length=255, unique=True)
    image = models.ImageField('Фото', upload_to=path_category_image,
                              default='images/default.jpg')
    is_published = models.BooleanField('Видимость', default=True)

    objects = models.Manager()
    published = PublishedManager()

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self) -> str:
        return reverse('core:category', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['name']


class PriceImport(models.Model):
    csv_file = models.FileField('Файл', upload_to='uploads/')
    date_added = models.DateTimeField('Дата загрузки', auto_now_add=True)

    class Meta:
        verbose_name = 'Импорт цен'
        verbose_name_plural = 'Импорт цен'
        ordering = ['-date_added']


class Carousel(models.Model):
    description = models.CharField('Описание', max_length=100)
    image = models.ImageField('Изображение', upload_to='images/carousel/')
    is_published = models.BooleanField('Видимость', default=True)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        verbose_name = 'Карусель'
        verbose_name_plural = 'Карусель'

core/forms.py
from django import forms
from django.forms import ModelForm
from core.models import PriceImport


class PriceImportForm(ModelForm):
    change_packs = forms.BooleanField(label='Автоматически изменять доступность',
                                      required=False)

    class Meta:
        model = PriceImport
        fields = ('csv_file',)

core/views.py
from django.forms import formset_factory
from django.views.generic import ListView, DetailView
from django.views.generic.base import TemplateView

from cart.forms import CartAddProductForm, BaseAddProductFormSet
from core.models import Product, Category, Carousel


class HomePageView(TemplateView):

    template_name = 'core/homepage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная'
        context['carousel'] = Carousel.published.all()
        return context


class ProductsListView(ListView):

    template_name = 'core/category.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.published.filter(type__category__slug=self.kwargs['slug'])\
            .select_related('type__category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Category.published.get(slug=self.kwargs['slug']).name
        context['current_cat'] = self.kwargs['slug']
        return context


class ProductView(DetailView):

    template_name = 'core/product.html'

    def get_queryset(self):
        return Product.published.select_related('productdetail')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            ProductFormSet = formset_factory(CartAddProductForm,
                                             formset=BaseAddProductFormSet,
                                             extra=0)
            packs = self.object.pack.filter(is_published=True)
            initial = tuple(packs.values('sku'))
            formset = ProductFormSet(initial=initial)
            context['cart_add_formset_with_packs'] = zip(packs, formset)
            context['management_form'] = formset.management_form
        context['title'] = self.object.name
        return context


class ProfileView(TemplateView):

    template_name = 'core/profile.html'
    slug_field = 'username'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context

core/templates/core/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
    {% load static %}
    <meta charset="utf-8">
    <title>{% block title %} {{ title }} {% endblock %}</title>
    <link type="text/css" href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'core/images/main.ico' %}" type="image/x-icon" />
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"
        defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.min.js"
        integrity="sha384-heAjqF+bCxXpCWLa6Zhcp4fu20XoNIA98ecBC1YkdXhszjoejr5y9Q77hIrv8R9i" crossorigin="anonymous"
        defer></script>
</head>
<body>
<div class="row">
  <div class="col-2 bg-dark" style="padding-top: 2%;">
    <div class="d-grid">
      <ul style="padding: 3%;">
      {% if request.user.is_authenticated %}
      <a href="{% url "core:profile" %}"><button type="button" class="btn btn-outline-light d-grid gap-1 mx-auto" style="padding-bottom: 3%;">Профиль</button></a>
      <li>
      {% with total_items=request.user.cart.count %}
        {% if total_items > 0 %}
          <a href="{% url "cart:cart_detail" %}">
        {% endif %}
            <button type="button" class="btn btn-outline-light d-grid gap-1 mx-auto" style="padding-bottom: 3%;">Корзина: {{ total_items }}</button>
          </a>
        </li>
        <li><a href="{% url "logout" %}"><button type="button" class="btn btn-outline-light d-grid gap-1 mx-auto" style="padding-bottom: 3%;">Выход</button></a></li>
      {% endwith %}
      {% else %}
        <a href="{% url "login" %}"><button type="button" class="btn btn-outline-light d-grid gap-1 mx-auto" style="padding-bottom: 3%;">Вход</button></a>
      {% endif %}
    </ul>
    </div>
  {% block menu %}
    <div class="btn-group-vertical d-grid gap-1 mx-auto" style="padding-top: 25%;" role="group" aria-label="Vertical button group">
        <a type="button" class="btn btn-outline-light" href="{% url 'core:home' %}" role="button">Главная</a>
        <div class="btn-group dropend" role="group">
            <button type="button" class="btn btn-outline-light dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              Компания
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">О компании</a></li>
              <li><a class="dropdown-item" href="#">Миссия</a></li>
              <li><a class="dropdown-item" href="#">Вакансии</a></li>
              <li><a class="dropdown-item" href="#">Награды и достижения</a></li>
            </ul>
        </div>
        <div class="btn-group dropend" role="group">
            <button type="button" class="btn btn-outline-light dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              Продукция
            </button>
            <ul class="dropdown-menu">
              {% for item in categories %}
              <li><a class="dropdown-item" href="{% url 'core:category' item.slug %}">{{ item }}</a></li>
              {% endfor %}
            </ul>
        </div>
        <a type="button" class="btn btn-outline-light" href="{% url 'core:home' %}" role="button">Где купить</a>
        <div class="btn-group dropend" role="group">
            <button type="button" class="btn btn-outline-light dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              Сотрудничество
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'cooperation:distribution' %}">Дистрибьюция </a></li>
              <li><a class="dropdown-item" href="{% url 'cooperation:private_label' %}">Private label</a></li>
              <li><a class="dropdown-item" href="{% url 'cooperation:suppliers' %}">Поставщикам</a></li>
              <li><a class="dropdown-item" href="#">Тендеры</a></li>
            </ul>
        </div>
        <a type="button" class="btn btn-outline-light" href="{% url 'core:home' %}" role="button">Новости</a>
        <a type="button" class="btn btn-outline-light" href="{% url 'core:home' %}" role="button">Вакансии</a>
        <a type="button" class="btn btn-outline-light" href="{% url 'core:home' %}" role="button">Контакты</a>
    </div>
  {% endblock %}
  </div>
  <div class="col" style="background-color: rgb(186, 247, 255);">
    {% block content %}{% endblock %}
  </div>
</div>
</body>
</html>

core/templates/core/category.html
{% extends 'core/base.html' %}

{% block content %}
<ul class="nav nav-underline" style="background-color: blanchedalmond; padding-inline: 15%;">
    {% for cat in categories %}
    <li class="nav-item">
      <a class="nav-link {% if current_cat == cat.slug %}active" 
      aria-current="page{% endif %}" style="color: red;" 
      href="{% url 'core:category' cat.slug %}">{{ cat }}</a>
    </li>
    {% endfor %}
  </ul>
<div class="row" style="padding-top: 15px;">
    <div class="col">
        <div class="row row-cols row-cols-md-6 g-4">
                {% for product in products %}
                <div class="col">
                    <a href="{% url 'core:product' product.slug %}">
                        <div class="card h-100 text-center">
                            <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product }}">
                            <div class="card-body">
                              <h6 class="card-title">{{ product }}</h6>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
        </div>
    </div>
    </div>

{% endblock %}

core/templates/core/homepage.html
{% extends 'core/base.html' %}

{% block content %}

<div id="carouselExample" class="carousel slide">
    <div class="carousel-inner">
        {% for item in carousel %}
      <div class="carousel-item {% if forloop.counter0 %} active {% endif %}">
        <img src="{{ item.image.url }}" class="d-block w-100" alt="...">
      </div>
        {% endfor %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
<div class="row" style="padding: auto;">
    <div class="col">
        <div class="row row-cols row-cols-md-6 g-4">
                {% for cat in categories %}
                <div class="col">
                    <a href="{% url 'core:category' cat.slug %}">
                        <div class="card h-100 text-center">
                            <img src="{{ cat.image.url }}" class="card-img-top" alt="{{ cat }}">
                            <div class="card-body">
                              <h6 class="card-title">{{ cat }}</h6>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
        </div>
    </div>
    </div>

{% endblock %}

core/templates/core/product.html
{% extends 'core/base.html' %}
{% load static %}
{% load weight_converter %}

{% block content %}

<h2>{{ product.name }}</h2>
{% if product.is_gost %}
<img src="{% static "img/gost.jpg" %}" alt="ГОСТ">
{% endif %}
<img src="{{ product.image.url }}">
<br>
<table class="table table-primary">
    <tbody>
      <tr>
        <th  scope="row">Описание</th>
        <td>{{ product.productdetail.description }}</td>
      </tr>
      <tr>
        <th scope="row">Условия хранения:</th>
        <td>{{ product.productdetail.conditions }}</td>
      </tr>
      <tr>
        <th scope="row">Срок хранения</th>
        <td>{{ product.productdetail.storage_time }} {{ product.productdetail.get_storage_time_units_display }}</td>
      </tr>
      <tr>
        <th scope="row">КБЖУ</th>
        <td>калорийность: {{ product.productdetail.calories|floatformat }} ккал<br>
            белки: {{ product.productdetail.proteins|floatformat }} г<br> 
            жиры: {{ product.productdetail.fats|floatformat }} г<br>
            углеводы: {{ product.productdetail.carbohydrates|floatformat }} г
        </td>
      </tr>
    </tbody>
</table>
{% if request.user.is_authenticated %}
<div class="container">
<form action="{% url "cart:cart_add" %}" method="post">
  {{ management_form }}
  <ul>
    {% for pack, form in cart_add_formset_with_packs %}
      <li>Вес: {{ pack.weight | convert_weight }}, в коробке {{ pack.items_in_box }} шт, общий вес {{ pack.get_package_weight | convert_weight }}. Цена: {{ pack.get_package_price }} {{ form }}</li>
    {% endfor %}
  </ul>
  {% csrf_token %}
  <input type="submit" value="Добавить в корзину">
 </form>
</div>
{% endif %}
 
{% endblock %}

core/templates/core/profile.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}{{ user.username}}{% endblock %}

{% block content %}
  <h3>{{ user.username }}</h3>
  <div class="btn-group-vertical" role="group" aria-label="Vertical button group">
    <a type="button" class="btn btn-outline-dark" href="{% url "cart:cart_detail" %}">Корзина</a>
    <a type="button" class="btn btn-outline-dark" href="{% url "orders:orders_list" %}">Заказы</a>
  </div>
{% endblock %}